### PR TITLE
Work around SDK issue in v3.0-dev

### PR DESCRIPTION
**Pull request by kevmoo**
See https://github.com/dart-lang/sdk/issues/50756

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Review by natebosch — APPROVED** [review]

**Review by jakemac53 — APPROVED** [review]

**Comment by lrhn** [comment]
Issue should be fixed in SDK now. Consider reverting this workaround when possible.

**Comment by kevmoo** [comment]
@lrhn – do you have a commit? I need to wait until we have a dev release rolled

**Comment by kevmoo** [comment]
looks like https://github.com/dart-lang/sdk/releases/tag/3.0.0-227.0.dev

**Pull request merged**
