### PR TITLE
Improves private names of functions

### LINKED ISSUE #619: Generate better private names for private classes
Hi.

I'm using the package [freezed](https://pub.dev/packages/freezed) and when I use json_serializable with, this problem shows to me. So I add this line `// ignore: non_constant_identifier_names` and the problem does not show more. But I need to do it manually, can you add it in your package, will solve this borrying label in poblems tabs.

This is what was generated:
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ability-model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

// ignore: non_constant_identifier_names
_$_Ability _$_$_AbilityFromJson(Map<String, dynamic> json) {
  return _$_Ability(
    name: json['name'] as String,
    url: json['url'] as String,
    isHidden: json['isHidden'] as bool,
    slot: json['slot'] as int,
  );
}

// ignore: non_constant_identifier_names
Map<String, dynamic> _$_$_AbilityToJson(_$_Ability instance) =>
    <String, dynamic>{
      'name': instance.name,
      'url': instance.url,
      'isHidden': instance.isHidden,
      'slot': instance.slot,
    };
```

And it's the code:
```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'ability-model.freezed.dart';
part 'ability-model.g.dart';

@freezed
abstract class Ability with _$Ability {
  const factory Ability({
    @required String name,
    @required String url,
    @required bool isHidden,
    @required int slot,
  }) = _Ability;

  factory Ability.fromJson(Map<String, dynamic> json) =>
      _$AbilityFromJson(json);
}
```

I don't know if I'm doing something wrong, if so tell me what I need to do to solve this, thanks.

### PR DESCRIPTION
**Pull request by Ascenio**
Changes naming of `toJson` and `fromJson` such that this:
```dart
class _Person {
  // ...
}
```
generates this:
```dart
_Person _$PersonFromJson(Map<String, dynamic> json) {}
Map<String, dynamic> _$PersonToJson(Person instance) {}
```
instead of this:
```dart
_Person _$_PersonFromJson(Map<String, dynamic> json) {}
Map<String, dynamic> _$_PersonToJson(Person instance) {}
```
Closes #619.

### CODE REVIEW

**Comment by kevmoo** [comment]
I like this change...BUT...need to be careful because this is a breaking change for folks that already have the current setup working...hrm...

**Comment by Ascenio** [comment]
Wouldn't a `pub run build_runner build --delete-conflicting-outputs` be enough?

**Comment by Ascenio** [comment]
If not, then you could create a separate branch on which new breaking changes can be merged until next major version is released.

**Comment by kevmoo** [comment]
I started v5 here https://github.com/google/json_serializable.dart/pull/856 – will rebase this on top of that.

GREAT work getting the test in there! Thank you!

**Review by kevmoo — COMMENTED** [review]
Please add an entry to the changelog!

**Comment by Ascenio** [comment]
Sure. Should I add it under 5.0.0-dev?

**Comment by kevmoo** [comment]
> Sure. Should I add it under 5.0.0-dev?

Please!

**Comment by Ascenio** [comment]
Done ;)

**Pull request merged**
